be_simple_deployment:
  rsync:
    delete:     true
    options:    -cCvaL
  rules:
    project:
      ignore:   []
    eclipse:
      ignore:   [.settings, .buildpath, .project]
    netbeans:
      ignore:   [nbproject]
    phpstorm:
      ignore:   [.idea]
    git:
      ignore:   [.git, .git*]
    svn:
      ignore:   [.svn]
    symfony:
      ignore:   [/app/cache/*, /app/logs/*, /app/config/parameters.yml, /web/bundles/*, /web/uploads/*, /web/js/*, /web/css/*]
    hosting:
      ignore:   [/.htaccess, /.htpasswd, /web/.user.ini]
    system:
      ignore:   [._*, .DS_Store]
  commands:
    cache_clear:
      type:     symfony
      command:  cache:clear
    assetic_dump:
      type:     symfony
      command:  assetic:dump
    assets_install:
      type:     symfony
      command:  assets:install
    doctrine_schema_update_force:
      type:     symfony
      command:  doctrine:schema:update --force --complete
    doctrine_schema_update_dump:
      type:     symfony
      command:  doctrine:schema:update --dump-sql
  ssh:
    connect_methods:
      server_to_client:
         crypt: rijndael-cbc@lysator.liu.se, aes256-cbc, aes192-cbc, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, arcfour
      client_to_server:
         crypt: rijndael-cbc@lysator.liu.se, aes256-cbc, aes192-cbc, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, arcfour
    pubkey_file:  %deploy_pubkey_file%
    privkey_file: %deploy_privkey_file%
    passphrase:   %deploy_passphrase%
  servers:
    dev:
      host:             %deploy_host%
      username:         %deploy_user%
      path:             %deploy_path%
      rules:            [eclipse, netbeans, phpstorm, git, svn, symfony, hosting, system]
      commands:         [cache_clear, assets_install, assetic_dump, doctrine_schema_update_force]
      symfony_command:  %deploy_symfony_command%