ibrows_newsletter:
  mandants:
    default:    ThisTokenIsNotSoSecretChangeItdefault
    mandantA:   ThisTokenIsNotSoSecretChangeItMandantA
    mandantB:   ThisTokenIsNotSoSecretChangeItMandantB
  classes:
    model:
      mandant:      Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Mandant
      newsletter:   Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Newsletter
      subscriber:   Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Subscriber
      design:       Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Design
      user:         Ibrows\NewsletterSandboxBundle\Entity\Newsletter\User
      block:        Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Block
      group:        Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Group
      readlog:      Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Log\ReadLog
      sentlog:      Ibrows\NewsletterSandboxBundle\Entity\Newsletter\Log\SentLog
      sendsettings: Ibrows\NewsletterSandboxBundle\Entity\Newsletter\SendSettings
      mailjob:      Ibrows\NewsletterSandboxBundle\Entity\Newsletter\MailJob
  filesystem:
      block:
        directory:  %kernel.root_dir%/../web/uploads/block
        public:     /uploads/block