stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: "tinymce"
    tinymce_buttons:
        unsubscribelink:
            title: "Unsubscribe Link"
            image: "https://cdn1.iconfinder.com/data/icons/CrystalClear/22x22/actions/news_unsubscribe.png"
        now:
            title: "Now"
            image: "https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/48x48/calendar_2.png"
        gendertitle:
            title: "Gender Title"
            image: "https://cdn1.iconfinder.com/data/icons/sem_labs_icon_pack/icons/users_mixed_gender.png"
        statisticlogreadimage:
            title: "Statistics Image"
            image: "https://cdn3.iconfinder.com/data/icons/fatcow/32/chart_bar.png"
        readonlinelink:
            title: "Read Online Link"
            image: "https://cdn1.iconfinder.com/data/icons/24x24-free-pixel-icons/24/Online.png"
    theme:
        simple:
            mode: "textareas"
            theme: "advanced"
            plugins: "fullscreen,table"
            theme_advanced_buttons2: "unsubscribelink,now,gendertitle,statisticlogreadimage,readonlinelink"
            #theme_advanced_buttons2: "tablecontrols"